### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by JavaMaxim** [mraible/history-of-web-frameworks-timeline#9] opened 2018-02-16 16:48 UTC

**Comment by lofidewanto** [comment] 2019-05-16 09:46
- Add Vue.js and J2CL
- Add Vue GWT and Domino UI GWT
- Add Flutter
- Add PWA term (“progressive web apps” was coined in 2015 by designer Frances Berriman and Google Chrome engineer, Alex Russell: https://whatis.techtarget.com/definition/progressive-web-app-PWA)
- Update GWT, Angular, Vaadin, React, Bootstrap, JSF, Spring / Thymleaf, PrimeFaces, Wicket, Grails, jQuery

@mraible: you can assign this to me, I'm doing it right now.

**Comment by lofidewanto** [comment] 2019-05-16 11:05
Done, I made a pull request. Here is my result: https://github.com/lofidewanto/history-of-web-frameworks-timeline

**Closed as completed** 2019-05-16 13:49 UTC
